Repository duck-dynasty/duckbot, pull requests merged in 2021-11, with the labels that each got.

#377 remove restart_policy conditions in docker compose file
  docker-compose.yml
Labels: small change

#378 :robot: Add small chance of a grateful duckbot
  duckbot/cogs/robot/thanking_robot.py
  tests/cogs/robot/thanking_robot_test.py
Labels: enhancement, small change

#367 add slash command model class
  duckbot/slash/option.py
  duckbot/slash/slash_command.py
  tests/slash/slash_command_test.py
Labels: help wanted

#368 add slash command context class
  duckbot/slash/__init__.py
  duckbot/slash/context.py
  setup.py
  tests/fixtures/discord/__init__.py
  tests/fixtures/discord/channel.py
  tests/fixtures/discord/context.py
  tests/fixtures/discord/interaction.py
  tests/fixtures/discord/message.py
  tests/slash/context_test.py
Labels: help wanted

#380 avoid sending embeds that are too large in `!calc`
  duckbot/cogs/math/wolfram_alpha.py
  duckbot/util/embeds/__init__.py
  tests/cogs/math/wolfram_alpha_test.py
Labels: bug, small change

#376 ensure event exceptions are logged
  duckbot/__main__.py
  duckbot/logs/__init__.py
  duckbot/logs/define_logs.py
  duckbot/logs/exception_logs.py
  duckbot/logs/get_logs.py
  duckbot/logs/logging.py
  tests/logs/define_logs_test.py
  tests/logs/exception_logs_test.py
  tests/logs/get_logs_test.py
  tests/logs/logging_test.py
  tests/logs/setup_test.py
Labels: operational

#381 ensure exceptions from task loops are logged
  duckbot/__init__.py
  duckbot/_monkeypatch.py
  duckbot/logs/__init__.py
  duckbot/logs/logging.py
  tests/logs/logging_test.py
  tests/logs/loop_replacement_test.py
Labels: operational

#379 add @slash_command decorator
  duckbot/slash/__init__.py
  duckbot/slash/slash_command_decorator.py
  tests/slash/get_slash_command_test.py
  tests/slash/slash_command_decorator_test.py
Labels: help wanted

#383 publish logs to cloudwatch
  .aws/cloudformation.template.yml
Labels: operational

#387 correct healthcheck+logconfiguration order
  .aws/cloudformation.template.yml
Labels: bug, small change, deployment

#385 respond to slash command events
  duckbot/slash/__init__.py
  duckbot/slash/slash_command_handler.py
  tests/slash/setup_test.py
  tests/slash/slash_command_handler_test.py
Labels: help wanted

#389 :children_crossing: mark `/eightball` as a slash command
  duckbot/cogs/fortune/eightball.py
Labels: small change

#394 🐛 fix `/eightball` args ending with quotes
  duckbot/logs/logging.py
  duckbot/slash/context.py
  tests/slash/context_test.py
Labels: bug, small change

#382 :sparkles: add `!define` command to pull definitions from oxford dictionary
  .aws/cloudformation.template.yml
  .github/workflows/python-package.yml
  README.md
  docker-compose.yml
  duckbot/cogs/text/__init__.py
  duckbot/cogs/text/dictionary.py
  tests/cogs/text/dictionary_test.py
  tests/cogs/text/setup_test.py
  wiki/Commands.md
Labels: new command

#404 🚸 mark `/recipe` as a slash command
  duckbot/cogs/recipe/recipe.py
Labels: small change

#391 📌 pin dependencies to current versions
  pyproject.toml
  setup.py
Labels: small change, dependencies

#392 🚀 refer to ecs optimized ami directly from parameter store
  .aws/cloudformation.template.yml
Labels: deployment

#396 :children_crossing: mark `/weather` commands as slash commands
  duckbot/cogs/weather/weather.py
Labels: small change

#399 🔨 create `format` entry point to run all the formatter tools
  .github/pull_request_template.md
  README.md
  setup.py
Labels: small change

#408 :pencil2: fix typo in exception message
  duckbot/slash/slash_command_decorator.py
Labels: small change

#409 🎨 load all available extensions in `duckbot.cogs` automatically
  duckbot/__main__.py
  tests/main_test.py
Labels: small change, cleanup

#407 :see_no_evil: correctly ignore logs directory
  .gitignore
Labels: small change

#410 :sparkles: :egg: add male kelly's birthday
  duckbot/cogs/announce_day/special_days.py
  tests/cogs/announce_day/announce_day_test.py
Labels: small change

#398 🎨 add markdown formatter + pytest plugin to verify it was run
  .github/pull_request_template.md
  README.md
  pyproject.toml
  setup.py
  tests/README.md
  tests/conftest.py
  tests/fixtures/mdformat/__init__.py
  wiki/Commands.md
  wiki/Events.md
  wiki/Home.md
  wiki/Logs.md
Labels: cleanup

#402 🚸 mark `/dice` as a slash command
  duckbot/cogs/games/dice.py
Labels: small change

#412 :construction_worker: update codecov action to v2
  .github/workflows/python-package.yml
Labels: dependencies

#417 :construction_worker: remove autoupdate pull requests
  .github/workflows/update-pull-requests.yml
Labels: bug, small change

#416 :art: Weather: Change snow bar colour to Cyan
  duckbot/cogs/weather/weather.py
Labels: small change

#418 :white_check_mark: Weather: Update test to include 24 hours
  tests/cogs/weather/weather_test.py
Labels: small change, cleanup

#425 ✨ add black friday special day
  duckbot/cogs/announce_day/special_days.py
  tests/cogs/announce_day/special_days_test.py
Labels: small change

#421 :children_crossing: mark `/define` as a slash command
  duckbot/cogs/text/dictionary.py
Labels: small change

#432 ✨ `!mock` replies to message if the command is a reply
  duckbot/cogs/text/mock_text.py
  tests/cogs/text/mock_text_test.py
Labels: small change

#429 🐛 show skipped checks as successful in `!yolo`
  duckbot/cogs/github/yolo_merge.py
  tests/cogs/github/yolo_merge_test.py
Labels: bug, small change
