Repository duck-dynasty/duckbot, pull requests merged in 2021-09, with the labels that each got.

#309 add BANG to list of F1 phrases
  duckbot/cogs/formula_one/phrases.py
Labels: small change

#310 upgrade discord.py to 2.0 + support threads
  duckbot/cogs/formula_one/formula_one.py
  duckbot/cogs/insights/insights.py
  setup.py
  tests/cogs/announce_day/announce_day_test.py
  tests/cogs/audio/who_can_it_be_now_test.py
  tests/cogs/formula_one/formula_one_test.py
  tests/cogs/insights/insights_test.py
  tests/conftest.py
  tests/duckmock/datetime/__init__.py
Labels: dependencies

#313 use named format strings in day of the week announcement
  duckbot/cogs/announce_day/announce_day.py
  duckbot/cogs/announce_day/phrases.py
  tests/cogs/announce_day/announce_day_test.py
Labels: small change

#312 add pep8 naming convention check to flake8
  setup.py
Labels: small change, dependencies

#315 avoid accessing `channel.name` for types that don't have a name
  duckbot/cogs/formula_one/formula_one.py
  tests/cogs/formula_one/formula_one_test.py
Labels: small change

#323 change docker image to `duckdynasty/duckbot`
  .github/workflows/python-package.yml
  docker-compose.yml
Labels: small change

#325 add thx as trigger word for thanking duckbot + only respond once
  duckbot/cogs/robot/thanking_robot.py
  tests/cogs/robot/thanking_robot_test.py
Labels: bug, small change

#326 setup dependabot to check for out of date dependencies
  .github/dependabot.yml
Labels: dependencies

#327 deploy duckbot to aws
  .aws/cloudformation.template.yml
  .github/workflows/python-package.yml
  Dockerfile
  docker-compose.yml
  production.yml
Labels: operational
