Repository duck-dynasty/duckbot, pull requests merged in 2022-08, with the labels that each got.

#565 💚 enable "legacy-editable" mode for setuptools
  .github/actions/setup-python-venv/action.yml
  README.md
Labels: small change, deployment

#564 add a "consider flossing" day of the week phrase
  duckbot/cogs/announce_day/phrases.py
Labels: small change

#566 💣 Remove Gloomhaven from one of the duckbot activities
  duckbot/cogs/games/discord_activity.py
Labels: enhancement, small change
