Repository duck-dynasty/duckbot, pull requests merged in 2022-11, with the labels that each got.

#601 🚀 scale down overnight
  .aws/duckdeploy/stack.py
Labels: deployment

#621 :date: :gift: Birthday --- Add Male Kelly's maybe birthday
  duckbot/cogs/announce_day/special_days.py
Labels: enhancement, small change

#623 :broom: Rename/correct duck test names
  tests/cogs/duck/duck_test.py
Labels: cleanup

#622 ⬆️ Bump pytest_sugar from 0.9.5 to 0.9.6
  setup.py
Labels: dependencies

#625 👷 replace LGTM scanning with codeql
  .github/workflows/code-analysis.yml
  README.md
Labels: dependencies
