Repository duck-dynasty/duckbot, pull requests merged in 2022-12, with the labels that each got.

#624 👷 address github actions set-output deprecation
  .github/actions/build-push-docker-image/action.yml
  .github/actions/setup-aws-cdk/action.yml
  .github/actions/setup-python-venv/action.yml
  .github/workflows/python-package.yml
Labels: dependencies, github_actions

#647 Commands --- Add `!wiki` as an alias for `!help` :microscope:
  duckbot/cogs/duck/duck.py
  wiki/Commands.md
Labels: small change

#648 :bug: Readme --- Fix badge url :microscope:
  README.md
Labels: bug, small change
