Repository duck-dynasty/duckbot, pull requests merged in 2023-01, with the labels that each got.

#667 Change to `pytest-flake8-v2`
  setup.py
Labels: dependencies

#668 🐛 wrap `/define` in typing
  duckbot/cogs/text/dictionary.py
Labels: small change

#670 💬 change typo correction message
  duckbot/cogs/corrections/typos.py
  tests/cogs/corrections/typos_test.py
Labels: small change

#672 Move custom datetime util
  duckbot/cogs/announce_day/announce_day.py
  duckbot/cogs/announce_day/special_days.py
  duckbot/util/datetime/__init__.py
  duckbot/util/datetime/datetime.py
  tests/cogs/announce_day/special_days_test.py
  tests/util/datetime/__init__.py
  tests/util/datetime/datetime_test.py
Labels: cleanup

#674 📝 Wiki Commands --- Reorder things 🔬
  wiki/Commands.md
Labels: documentation, small change
